### ISSUE TITLE
Add examples for `list(range(10))` (and with `_mode_`)

### ISSUE THREAD

**Issue by bagxi** [catalyst-team/hydra-slayer#27]
```yaml
a:
  _target_: list
  iterable:
    _target_: range
    start: 0
    stop: 10
    step: 1
    _mode_: call
  _mode_: call
```
